# Generated by Django 5.2.10 on 2026-01-28 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentdataset',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Equipment Dataset', 'verbose_name_plural': 'Equipment Datasets'},
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_datasets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
